services:
  frontend:
    depends_on:
      - backend
    container_name: task-manager-frontend
    build:
      context: ./task-manager-frontend
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      - VITE_DOMAIN_NAME=task-manager.space
    image: bering152/task-manager-frontend:latest
    restart: on-failure
    ports:
      - 127.0.0.1:3000:8080

  backend:
    depends_on:
      db:
        condition: service_healthy
    container_name: task-manager-backend
    build:
      context: ./task-manager-backend
    env_file:
      - ./task-manager-backend/.env.production
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    image: bering152/task-manager-backend:latest
    restart: on-failure
    ports:
      - 127.0.0.1:5000:8080

  redis:
    container_name: task-manager-redis
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis-data:/data
    image: redis:7
    restart: on-failure
    ports:
      - "127.0.0.1:6379:6379"

  db:
    container_name: task-manager-database
    env_file:
      - ./task-manager-database/.env.production
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    image: postgres:15
    restart: on-failure
    ports:
      - 127.0.0.1:5433:5432

volumes:
  db-data:
    name: task-manager-db-data
  redis-data:
    name: task-manager-redis-data
